### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by jordan-heemskerk** [jenzb/WonderDoIt#1]
Hi @jenzb 

I see that you no longer have time to support this project. I'm a developer and this Alexa skill was amazing to have. I'd be happy to contribute or assume ownership of the skill to maintain it going forward. 

Would you consider adding me as a maintainer?

**Comment by jensbuehl** [comment]
Hi Jordan, I would be more than happy if the journey continues, and somebody picks up the work. Someday I will have more spare time and can join the development again.

So next, I need your resume and referen...nah, just kidding. ;)

We could also discuss access to the AWS lambda and the Alexa Skill Developer Console so that you could re-use the infrastructure that is already in place. For now, I will make you repo maintainer.
